package exercises

func Solve002() int {
	// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
	// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
	nums := []int{1, 2}
	next_num := 0
	result := 2
	limit := 4000000
	for i := 0; next_num < limit; i++ {
		next_num = nums[i] + nums[i+1]
		nums = append(nums, next_num)
		if next_num%2 == 0 {
			result += next_num
		}
	}
	return result
}
